### ISSUE TITLE
Session 7 Report

### ISSUE THREAD

**Issue by mohammadali-seifkashani** [Sharif-OS-Lab/session-7#4]
Team Name: summer1400-g3-4-97106024-96105961`

Student Name of member 1: `محمدکاظم فقیه`
Student No. of member 1: `96105961`

Student Name of member 2: `محمدعلی سیف کاشانی`
Student No. of member 2: `97106024`

- [ ] Read Session Contents.

### Section 7.4.1
- [ ] Creating a thread using pthread
    - [ ] ![os20](https://user-images.githubusercontent.com/45390101/130655156-fd244f9a-f718-450f-b98d-d45920deef4e.png)

   
- [ ]  Checking the process ids
    - [ ] ![os21](https://user-images.githubusercontent.com/45390101/130654727-c0ec26d7-1de6-413b-9487-5f5bd5933680.png)
    - [ ] بله شماره ها یکسان است.

- [ ]  Shared variables
    - [ ] ![os22](https://user-images.githubusercontent.com/45390101/130655770-877b99c1-f090-4f90-a923-19061b21fb82.png)
    - [ ]  `متغیر به صورت عمومی تعریف شده و در هر دو ریسه همان متغیر و نه کپی جداگانه از آن استفاده شده. هر دو ریسه جداگانه به (آدرس) همان متغیر دسترسی دارند ولی درصورت تغییر دادن در یک زمان قفل آن صرفا دست یک ریسه خواهد بود.`

- [ ] Sum of 2 to n
    1. [ ] ![os23](https://user-images.githubusercontent.com/45390101/130662790-70023a9c-2de1-4745-b39a-9ba8cb3e789f.png)
    1. [ ] ![os24](https://user-images.githubusercontent.com/45390101/130662894-8bb920fb-b59a-4a4b-950c-479433ad56fe.png)

### Section 7.4.2
- [ ] Multiple threads    
    - [ ] ![os25](https://user-images.githubusercontent.com/45390101/130665654-6bd2f6eb-9c5b-4a35-a13b-21a703077d58.png)
    - [ ] ![os26](https://user-images.githubusercontent.com/45390101/130665599-e45aa29a-c76b-4585-8ce0-e28256be1eb9.png)

### Section 7.4.3
- [ ] Compiling the code
    - [ ] ![7 4 3 1-2](https://user-images.githubusercontent.com/45390101/130671099-fa022bbe-4869-4f3f-8a60-27aaf2daa6aa.png)

- [ ] global_param
    - [ ] ![7 4 3 2-1](https://user-images.githubusercontent.com/45390101/130671493-8f1e74a2-fe33-4829-9556-3b49f78500f7.png)
    - [ ] ![7 4 3 2-2](https://user-images.githubusercontent.com/45390101/130671549-e81b326d-2d9a-41b9-b13c-18533f3ae44c.png)

- [ ] Forking
    - [ ] ![7 4 3 3-1](https://user-images.githubusercontent.com/45390101/130671655-622baf93-5558-4cd4-9ceb-59dc87d436a4.png)
    - [ ] ![7 4 3 3-2](https://user-images.githubusercontent.com/45390101/130671686-1a5dd6c5-e3d3-49ac-853e-2b51ae5d70d1.png)

### Section 7.4.4
- [ ] Passing multiple variables
    - [ ] ![7 4 4-1](https://user-images.githubusercontent.com/45390101/130671775-4fd796f8-3e31-4779-a2c0-517a2107e43d.png)
    - [ ] ![7 4 4-2](https://user-images.githubusercontent.com/45390101/130671812-eb1495d8-0f2c-4eb6-9c1a-c1c846261427.png)

**Comment by alimirferdos** [comment]
100
